"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
export default function Profile(){
 const [name,setName]=useState(""); const [data,setData]=useState<any>(null); const [error,setError]=useState("");
 useEffect(()=>{try{const n=localStorage.getItem("daily-guess:last-player");if(n)setName(n)}catch{}},[]);
 async function load(e?:React.FormEvent){e?.preventDefault();setError("");if(!name.trim())return;try{localStorage.setItem("daily-guess:last-player",name.trim());const r=await fetch(`/api/player/stats?name=${encodeURIComponent(name.trim())}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j)}catch(e:any){setError(e.message||"Could not load profile.")}}
 return <section className="card" style={{marginTop:40}}><div className="eyebrow">PLAYER PROFILE</div><h1>Your stats</h1><form onSubmit={load} className="player-profile-form"><div className="field"><label>Leaderboard name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your leaderboard name"/></div><button className="btn full">View my stats</button></form>{error&&<div className="error">{error}</div>}{data&&<><div className="profile-grid"><div><b>{data.currentStreak} 🔥</b><span>Current streak</span></div><div><b>{data.best}/16</b><span>Personal best</span></div><div><b>{data.average.toFixed(1)}/16</b><span>Average score</span></div><div><b>{data.totalCorrect}</b><span>Correct answers</span></div><div><b>💡 {data.totalClues||0}</b><span>Clues used</span></div></div><h2>Achievements</h2><div className="achievement-grid">{data.achievements.map((a:any)=><div className="achievement" key={a.id}><span>{a.icon}</span><b>{a.name}</b><small>{a.desc}</small></div>)}{!data.achievements.length&&<p className="muted">Keep playing to unlock achievements.</p>}</div><h2>Past days</h2>{data.days.map((d:any)=><div className="past-day" key={d.date}><div><b>{d.date}</b><span className="muted small"> {d.completed}/4 challenges</span></div><b>{d.score}/16</b></div>)}</>}<Link className="btn secondary full" href="/leaderboard">Leaderboard</Link></section>
}
