"use client";
import {useEffect,useRef,useState} from "react";
import Countdown from "./Countdown";

type Challenge={id:string;slot:number;title:string;posterUrl:string|null;difficulty:string};
type Result={score:number;breakdown:any[]};
type SavedDay={playerName:string;current:number;results:Result[];done:boolean;form:{name:string;age:string;occupation:string;from:string};confidence:Record<string,string>;replays:number[]};
const emptyForm={name:"",age:"",occupation:"",from:""};
const qLabels=["name","age","occupation","from"] as const;
const confOptions=["Guessing","Fairly confident","Certain"];

export default function Game({date,challenges,dayNumber}:{date:string;challenges:Challenge[];dayNumber:number}){
 const [playerName,setPlayerName]=useState("");const [current,setCurrent]=useState(0);const [results,setResults]=useState<Result[]>([]);const [done,setDone]=useState(false);const [unlocked,setUnlocked]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [videoUrl,setVideoUrl]=useState<string|null>(null);const [form,setForm]=useState(emptyForm);const [confidence,setConfidence]=useState<Record<string,string>>({});const [replays,setReplays]=useState<number[]>([]);const [loaded,setLoaded]=useState(false);const [startedAt,setStartedAt]=useState(Date.now());const [videoTime,setVideoTime]=useState(0);const [videoDuration,setVideoDuration]=useState(0);
 const v=useRef<HTMLVideoElement>(null);const storageKey=`daily-guess:${date}`;const challenge=challenges[current];
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw) as SavedDay;setPlayerName(saved.playerName||"");setCurrent(Math.min(saved.current||0,Math.max(challenges.length-1,0)));setResults(Array.isArray(saved.results)?saved.results:[]);setDone(Boolean(saved.done));if(saved.form)setForm(saved.form);if(saved.confidence)setConfidence(saved.confidence);if(saved.replays)setReplays(saved.replays)}}catch{}setLoaded(true)},[date,storageKey,challenges.length]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(storageKey,JSON.stringify({playerName,current,results,done,form,confidence,replays} as SavedDay));if(playerName) localStorage.setItem("daily-guess:last-player",playerName)}catch{}},[loaded,storageKey,playerName,current,results,done,form,confidence,replays]);
 useEffect(()=>{setUnlocked(Boolean(results[current]));setVideoUrl(null);setStartedAt(Date.now());setVideoTime(0);setVideoDuration(0);const x=v.current;if(x){x.pause();x.currentTime=0;x.load()}if(results[current]&&playerName.trim()&&challenge){fetch(`/api/video/${challenge.id}?date=${encodeURIComponent(date)}&displayName=${encodeURIComponent(playerName.trim())}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(j=>setVideoUrl(j.videoUrl)).catch(()=>{})}},[current,results,date,playerName,challenge?.id]);
 useEffect(()=>{const x=v.current;if(!x)return;const f=()=>{if(!unlocked){x.pause();x.currentTime=0}};x.addEventListener("play",f);return()=>x.removeEventListener("play",f)},[unlocked]);
 const update=(k:string,val:string)=>setForm({...form,[k]:val});const setConf=(k:string,val:string)=>setConfidence({...confidence,[k]:val});
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!challenge)return;if(!playerName.trim()){setError("Please enter your player name first.");return}if(qLabels.some(k=>!confidence[k])){setError("Please choose how confident you are for each answer.");return}setBusy(true);setError("");try{const elapsed=Math.max(1,Math.round((Date.now()-startedAt)/1000));const r=await fetch("/api/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({challengeId:challenge.id,date,displayName:playerName.trim(),answers:form,confidence,elapsedSeconds:elapsed})});const j=await r.json();if(!r.ok)throw Error(j.error||"Submission failed.");setResults(prev=>[...prev,j]);setUnlocked(true);try{const vr=await fetch(`/api/video/${challenge.id}?date=${encodeURIComponent(date)}&displayName=${encodeURIComponent(playerName.trim())}`,{cache:"no-store"});if(vr.ok)setVideoUrl((await vr.json()).videoUrl)}catch{}if(current===challenges.length-1)setDone(true)}catch(e:any){setError(e.message||"Submission failed")}finally{setBusy(false)}}
 function replay(){setReplays(prev=>{const next=[...prev];next[current]=(next[current]||0)+1;return next});v.current?.play().catch(()=>{})}
 const total=results.reduce((n,r)=>n+r.score,0);
 if(!loaded)return <section className="card"><p className="muted">Loading today’s challenge…</p></section>;
 if(done)return <DailyStats date={date} dayNumber={dayNumber} playerName={playerName} results={results} total={total} replays={replays}/>;
 if(!challenge)return <section className="card"><h2>No challenges published yet.</h2></section>;
 return <>
  <section className="hero"><div className="eyebrow">DAY #{dayNumber} · {date} · CHALLENGE {current+1} OF {challenges.length}</div><h1>Daily Guess</h1><p>Four clips. Four guesses each. Maximum score: 16.</p></section>
  <section className="card">
   <div className="progress"><span style={{width:`${(current/challenges.length)*100}%`}}/></div>
   <div className="challenge-meta"><span className="pill">{challenge.difficulty.toUpperCase()}</span><span className="muted small">Challenge {current+1}/4</span></div>
   <div className="player-field field"><label>Your leaderboard name</label><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="Enter the name you want shown" disabled={results.length>current}/><span className="muted small">Separate from your “Name” guess.</span></div>
   <div className="video"><video key={`${challenge.id}-${videoUrl||"locked"}`} ref={v} src={videoUrl||undefined} poster={challenge.posterUrl||undefined} playsInline controls={unlocked&&!!videoUrl} onTimeUpdate={e=>setVideoTime(e.currentTarget.currentTime)} onLoadedMetadata={e=>setVideoDuration(e.currentTarget.duration)}/>{!unlocked&&<div className="locked-badge"><span>🔒</span><div><b>Video locked</b><div className="muted small">Submit your four guesses to play</div></div></div>}</div>
   {unlocked&&videoUrl&&<div className="video-time">▶ {Math.floor(videoTime/60)}:{String(Math.floor(videoTime%60)).padStart(2,"0")} / {Math.floor(videoDuration/60)}:{String(Math.floor(videoDuration%60)).padStart(2,"0")}</div>}
   <form onSubmit={submit}>
    <div className="questions">{qLabels.map(k=><div className="field" key={k}><label>{k==="from"?"Where are they from?":k[0].toUpperCase()+k.slice(1)}</label><input required value={(form as any)[k]} onChange={e=>update(k,e.target.value)} inputMode={k==="age"?"numeric":undefined} disabled={unlocked}/><div className="confidence">{confOptions.map(c=><button type="button" key={c} className={confidence[k]===c?"confidence-btn selected":"confidence-btn"} onClick={()=>setConf(k,c)} disabled={unlocked}>{c}</button>)}</div></div>)}</div>
    {error&&<div className="error" style={{marginTop:14}}>{error}</div>}{!unlocked&&<button className="btn full" disabled={busy}>{busy?"Checking guesses…":`Submit challenge ${current+1}`}</button>}
   </form>
  </section>
  {results[current] ? <ResultCard result={results[current]} replayCount={replays[current]||0} replay={replay} done={done} next={()=>{setCurrent(current+1);setForm(emptyForm);setConfidence({})}}/> : null}
 </>;
}

function DailyStats({date,dayNumber,playerName,results,total,replays}:{date:string;dayNumber:number;playerName:string;results:Result[];total:number;replays:number[]}){
 const [stats,setStats]=useState<any>(null);useEffect(()=>{fetch(`/api/player/stats?name=${encodeURIComponent(playerName)}`,{cache:"no-store"}).then(r=>r.json()).then(setStats).catch(()=>{})},[playerName]);
 const correct=results.reduce((n,r)=>n+r.score,0);const questions=results.length*4;const accuracy=questions?correct/questions*100:0;
 async function share(){const text=`I scored ${total}/16 on Daily Guess today! 🎯`;if(navigator.share)try{await navigator.share({title:"Daily Guess",text,url:location.origin})}catch{}else{await navigator.clipboard?.writeText(`${text} ${location.origin}`);alert("Score copied to clipboard!")}}
 return <section><section className="hero"><div className="eyebrow">DAY #{dayNumber} · {date} · DAILY RESULTS</div><h1>Your day</h1><p>You’ve completed all four challenges.</p></section><section className="card stats-summary"><div className="score">{total} / 16</div><div className="scoreline">{accuracy.toFixed(1)}% accuracy · leaderboard name: <b>{playerName}</b></div><div className="stat-pills"><span className="pill">🔥 {stats?.currentStreak||0} day streak</span><span className="pill">🏆 best {stats?.best||total}/16</span><span className="pill">⚡ fastest {stats?.fastest||"—"}s</span></div><button className="btn full" onClick={share}>Share my score</button></section>
 <section className="card"><div className="eyebrow">ACHIEVEMENTS</div><div className="achievement-grid">{(stats?.achievements||[]).map((a:any)=><div className="achievement" key={a.id}><span>{a.icon}</span><b>{a.name}</b><small>{a.desc}</small></div>)}{!stats?.achievements?.length&&<p className="muted">Keep playing to unlock achievements.</p>}</div></section>
 <section className="card"><div className="eyebrow">ALL ANSWERS</div><h2>Everything you guessed today</h2>{results.map((result,i)=><StatsChallenge key={i} result={result} index={i} replays={replays[i]||0}/>) }<Countdown/><a className="btn full" href="/leaderboard">View leaderboard</a><a className="btn secondary full" href="/profile">View full player profile</a></section></section>;
}

function ResultCard({result,replayCount,replay,done,next}:{result:Result;replayCount:number;replay:()=>void;done:boolean;next:()=>void}){return <section className="card"><div className="score">{result.score} / 4</div><div className="scoreline">Challenge score · {replayCount} replays</div>{result.breakdown.map((x:any)=><div className="answer" key={x.key}><b>{x.label}</b> <span className={x.correct?"ok":"no"}>{x.correct?"✓ Correct":"✗ Incorrect"}</span><div className="muted small">Your answer: {x.guess} · Correct: {x.correctAnswer}</div>{x.confidence&&<div className="muted small">Confidence: {x.confidence}</div>}</div>)}<button className="btn secondary full" onClick={replay}>Watch video again · {replayCount}</button>{!done&&<button className="btn full" onClick={next}>Next challenge →</button>}</section>}
function StatsChallenge({result,index,replays}:{result:Result;index:number;replays:number}){return <div className="stats-challenge"><div className="stats-heading"><b>Challenge {index+1}</b><span className="pill">{result.score}/4</span></div>{result.breakdown.map((x:any)=><div className="answer" key={x.key}><div className="stats-answer-heading"><b>{x.label}</b><span className={x.correct?"ok":"no"}>{x.correct?"✓ Correct":"✗ Incorrect"}</span></div><div className="muted small"><b>Your answer:</b> {x.guess||"—"}</div><div className="muted small"><b>Correct answer:</b> {x.correctAnswer}</div>{x.confidence&&<div className="muted small"><b>Confidence:</b> {x.confidence}</div>}</div>)}<div className="muted small">Replays: {replays}</div></div>}
